### ISSUE TITLE
Package installation with install_github()

### ISSUE THREAD

**Issue by merlevede** [CNRGH/crimmix#1]
Hello,

I would like to try your package but have an issue with the installation.
I tried to install it simply like this:
`devtools::install_github("CNRGH/crimmix")`
from R version 3.5.1 and 3.6.0

After suggesting to update some packages, the error is:
```
Skipping 5 packages not available: iClusterPlus, mixOmics, mogsa, omicade4, phyloseq
Installing 54 packages: ...
Installing packages into ...
Erreur : (converti depuis l'avis) packages ‘iClusterPlus’, ‘mixOmics’, ‘mogsa’, ‘omicade4’, ‘phyloseq’ are not available (for R version 3.5.1)
```

Could you please mention which R version did you use?
Should the installation of the different tested tools be performed prior to the installation of your package?
Thank you

**Comment by mpierrejean** [comment]
Hello,
It should work on the two versions.
The 5 packages cited above are on Bioconductor. Could you try:

`BiocManager::install(c("iClusterPlus", "mixOmics", "mogsa", "omicade4", "phyloseq"))
`

**Comment by merlevede** [comment]
Thank you.
Sorry, it was easy to correct indeed, I though the installation would be included.
So I installed the 5 packages (here using R 3.6.1). I also had to install several other packages: CIMLR, ConsensusClusterPlus, LRAcluster (from sources), PINSPlus and the installation is done.
